
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TodoWatchApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'PusherSwift'
  # Pods for ToDoWatchApp
end

target 'TodoWatchApp WatchKit App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Pods for ToDoWatchApp WatchKit App

end

target 'TodoWatchApp WatchKit Extension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Pods for ToDoWatchApp WatchKit Extension

end